# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn CDSS / TSTool
pages:
- Home: index.md
- 1 - Introduction: introduction.md
- 2 - Getting Started: getting-started.md
- 3 - Commands: commands.md
- 4 - Tools: tools.md
- 5 - Examples of Use: examples.md
- 6 - Quality Control: quality-control.md
- 7 - Spatial Data Integration: spatial.md
- 8 - Spreadsheet Integration: spreadsheet.md
- 9 - Model Framework Integration: modeling.md
- 10 - Troubleshooting: troubleshooting.md
- 11 - Best Practices:
  - Time Series Identifiers: best-practices/ts-identifiers.md
- 12 - Resources: resources.md
- Lessons:
  - Overview: lessons/overview.md
- Reference - Commands:
  - Overview: command-ref/overview.md
  - '# Comment': command-ref/Comment/Comment.md
  - '/* Comment Start': command-ref/CommentBlockStart/CommentBlockStart.md
  - '*/ Comment End': command-ref/CommentBlockEnd/CommentBlockEnd.md
  - Add: command-ref/Add/Add.md
  - AddConstant: command-ref/AddConstant/AddConstant.md
  - AdjustExtremes: command-ref/AdjustExtremes/AdjustExtremes.md
  - AnalyzePattern: command-ref/AnalyzePattern/AnalyzePattern.md
  - AppendFile: command-ref/AppendFile/AppendFile.md
  - AppendTable: command-ref/AppendTable/AppendTable.md
  - Blend: command-ref/Blend/Blend.md
  - ChangePeriod: command-ref/ChangePeriod/ChangePeriod.md
  - ChangeTimeZone: command-ref/ChangeTimeZone/ChangeTimeZone.md
  - CheckTimeSeries: command-ref/CheckTimeSeries/CheckTimeSeries.md
  - CheckTimeSeriesStatistic: command-ref/CheckTimeSeriesStatistic/CheckTimeSeriesStatistic.md
  - CloseDataStore: command-ref/CloseDataStore/CloseDataStore.md
  - CloseExcelWorkbook: command-ref/CloseExcelWorkbook/CloseExcelWorkbook.md
  - CompareFiles: command-ref/CompareFiles/CompareFiles.md
  - CompareTables: command-ref/CompareTables/CompareTables.md
  - CompareTimeSeries: command-ref/CompareTimeSeries/CompareTimeSeries.md
  - ComputeErrorTimeSeries: command-ref/ComputeErrorTimeSeries/ComputeErrorTimeSeries.md
  - ConvertDataUnits: command-ref/ConvertDataUnits/ConvertDataUnits.md
  - CopyFile: command-ref/CopyFile/CopyFile.md
  - Copy: command-ref/Copy/Copy.md
  - CopyEnsemble: command-ref/CopyEnsemble/CopyEnsemble.md
  - CopyTable: command-ref/CopyTable/CopyTable.md
  - CopyTimeSeriesPropertiesToTable: command-ref/CopyTimeSeriesPropertiesToTable/CopyTimeSeriesPropertiesToTable.md
  - CreateDataStoreDataDictionary: command-ref/CreateDataStoreDataDictionary/CreateDataStoreDataDictionary.md
  - CreateEnsembleFromOneTimeSeries: command-ref/CreateEnsembleFromOneTimeSeries/CreateEnsembleFromOneTimeSeries.md
  - CreateRegressionTestCommandFile: command-ref/CreateRegressionTestCommandFile/CreateRegressionTestCommandFile.md
  - CreateTimeSeriesEventTable: command-ref/CreateTimeSeriesEventTable/CreateTimeSeriesEventTable.md
  - Cumulate: command-ref/Cumulate/Cumulate.md
  - DeleteDataStoreTableRows: command-ref/DeleteDataStoreTableRows/DeleteDataStoreTableRows.md
  - DeleteTableColumns: command-ref/DeleteTableColumns/DeleteTableColumns.md
  - DeleteTableRows: command-ref/DeleteTableRows/DeleteTableRows.md
  - Delta: command-ref/Delta/Delta.md
  - DeselectTimeSeries: command-ref/DeselectTimeSeries/DeselectTimeSeries.md
  - Disaggregate: command-ref/Disaggregate/Disaggregate.md
  - Divide: command-ref/Divide/Divide.md
  - Empty: command-ref/Empty/Empty.md
  - EndFor: command-ref/EndFor/EndFor.md
  - EndIf: command-ref/EndIf/EndIf.md
  - Exit: command-ref/Exit/Exit.md
  - ExpandTemplateFile: command-ref/ExpandTemplateFile/ExpandTemplateFile.md
  - FillConstant: command-ref/FillConstant/FillConstant.md
  - FillFromTS: command-ref/FillFromTS/FillFromTS.md
  - FillHistMonthAverage: command-ref/FillHistMonthAverage/FillHistMonthAverage.md
  - FillHistYearAverage: command-ref/FillHistYearAverage/FillHistYearAverage.md
  - FillInterpolate: command-ref/FillInterpolate/FillInterpolate.md
  - FillPattern: command-ref/FillPattern/FillPattern.md
  - FillProrate: command-ref/FillProrate/FillProrate.md
  - FillRepeat: command-ref/FillRepeat/FillRepeat.md
  - For: command-ref/For/For.md
  - FormatDateTimeProperty: command-ref/FormatDateTimeProperty/FormatDateTimeProperty.md
  - FormatStringProperty: command-ref/FormatStringProperty/FormatStringProperty.md
  - FormatTableDateTime: command-ref/FormatTableDateTime/FormatTableDateTime.md
  - FormatTableString: command-ref/FormatTableString/FormatTableString.md
  - Free: command-ref/Free/Free.md
  - FreeTable: command-ref/FreeTable/FreeTable.md
  - FTPGet: command-ref/FTPGet/FTPGet.md
  - If: command-ref/If/If.md
  - InsertTableColumn: command-ref/InsertTableColumn/InsertTableColumn.md
  - InsertTableRow: command-ref/InsertTableRow/InsertTableRow.md
  - InsertTimeSeriesIntoEnsemble: command-ref/InsertTimeSeriesIntoEnsemble/InsertTimeSeriesIntoEnsemble.md
  - JoinTables: command-ref/JoinTables/JoinTables.md
  - ListFiles: command-ref/ListFiles/ListFiles.md
  - LookupTimeSeriesFromTable: command-ref/LookupTimeSeriesFromTable/LookupTimeSeriesFromTable.md
  - ManipulateTableString: command-ref/ManipulateTableString/ManipulateTableString.md
  - Message: command-ref/Message/Message.md
  - Multiply: command-ref/Multiply/Multiply.md
  - NewEnsemble: command-ref/NewEnsemble/NewEnsemble.md
  - NewExcelWorkbook: command-ref/NewExcelWorkbook/NewExcelWorkbook.md
  - NewEndOfMonthTSFromDayTS: command-ref/NewEndOfMonthTSFromDayTS/NewEndOfMonthTSFromDayTS.md
  - NewPatternTimeSeries: command-ref/NewPatternTimeSeries/NewPatternTimeSeries.md
  - NewStatisticEnsemble: command-ref/NewStatisticEnsemble/NewStatisticEnsemble.md
  - NewStatisticMonthTimeSeries: command-ref/NewStatisticMonthTimeSeries/NewStatisticMonthTimeSeries.md
  - NewStatisticTimeSeries: command-ref/NewStatisticTimeSeries/NewStatisticTimeSeries.md
  - NewTimeSeries: command-ref/NewTimeSeries/NewTimeSeries.md
  - NewTable: command-ref/NewTable/NewTable.md
  - NewTreeView: command-ref/NewTreeView/NewTreeView.md
  - Normalize: command-ref/Normalize/Normalize.md
  - PrintTextFile: command-ref/PrintTextFile/PrintTextFile.md
  - ProcessRasterGraph: command-ref/ProcessRasterGraph/ProcessRasterGraph.md
  - ProcessTSProduct: command-ref/ProcessTSProduct/ProcessTSProduct.md
  - ProfileCommands: command-ref/ProfileCommands/ProfileCommands.md
  - ReadDelimitedFile: command-ref/ReadDelimitedFile/ReadDelimitedFile.md
  - ReadPatternFile: command-ref/ReadPatternFile/ReadPatternFile.md
  - ReadPropertiesFromFile: command-ref/ReadPropertiesFromFile/ReadPropertiesFromFile.md
  - ResequenceTimeSeriesData: command-ref/ResequenceTimeSeriesData/ResequenceTimeSeriesData.md
  - ReadTableFromDataStore: command-ref/ReadTableFromDataStore/ReadTableFromDataStore.md
  - ReadTableFromDBF: command-ref/ReadTableFromDBF/ReadTableFromDBF.md
  - ReadTableFromDelimitedFile: command-ref/ReadTableFromDelimitedFile/ReadTableFromDelimitedFile.md
  - ReadTableFromExcel: command-ref/ReadTableFromExcel/ReadTableFromExcel.md
  - ReadTableFromFixedFormatFile: command-ref/ReadTableFromFixedFormatFile/ReadTableFromFixedFormatFile.md
  - ReadTableFromJSON: command-ref/ReadTableFromJSON/ReadTableFromJSON.md
  - ReadTableFromXml: command-ref/ReadTableFromXml/ReadTableFromXml.md
  - ReadTimeSeriesFromDataStore: command-ref/ReadTimeSeriesFromDataStore/ReadTimeSeriesFromDataStore.md
  - RelativeDiff: command-ref/RelativeDiff/RelativeDiff.md
  - RemoveFile: command-ref/RemoveFile/RemoveFile.md
  - ReplaceValue: command-ref/ReplaceValue/ReplaceValue.md
  - RunCommands: command-ref/RunCommands/RunCommands.md
  - RunDSSUTL: command-ref/RunDSSUTL/RunDSSUTL.md
  - RunProgram: command-ref/RunProgram/RunProgram.md
  - RunPython: command-ref/RunPython/RunPython.md
  - RunSql: command-ref/RunSQL/RunSql.md
  - Scale: command-ref/Scale/Scale.md
  - SelectTimeSeries: command-ref/SelectTimeSeries/SelectTimeSeries.md
  - SetAutoExtendPeriod: command-ref/SetAutoExtendPeriod/SetAutoExtendPeriod.md
  - SetAveragePeriod: command-ref/SetAveragePeriod/SetAveragePeriod.md
  - SetConstant: command-ref/SetConstant/SetConstant.md
  - SetDataValue: command-ref/SetDataValue/SetDataValue.md
  - SetDebugLevel: command-ref/SetDebugLevel/SetDebugLevel.md
  - SetEnsembleProperty: command-ref/SetEnsembleProperty/SetEnsembleProperty.md
  - SetFromTS: command-ref/SetFromTS/SetFromTS.md
  - SetIncludeMissingTS: command-ref/SetIncludeMissingTS/SetIncludeMissingTS.md
  - SetIgnoreLEZero: command-ref/SetIgnoreLEZero/SetIgnoreLEZero.md
  - SetInputPeriod: command-ref/SetInputPeriod/SetInputPeriod.md
  - SetOutputPeriod: command-ref/SetOutputPeriod/SetOutputPeriod.md
  - SetOutputYearType: command-ref/SetOutputYearType/SetOutputYearType.md
  - SetProperty: command-ref/SetProperty/SetProperty.md
  - SetPropertyFromEnsemble: command-ref/SetPropertyFromEnsemble/SetPropertyFromEnsemble.md
  - SetPropertyFromTable: command-ref/SetPropertyFromTable/SetPropertyFromTable.md
  - SetPropertyFromTimeSeries: command-ref/SetPropertyFromTimeSeries/SetPropertyFromTimeSeries.md
  - SetTableValues: command-ref/SetTableValues/SetTableValues.md
  - SetTimeSeriesProperty: command-ref/SetTimeSeriesProperty/SetTimeSeriesProperty.md
  - SetTimeSeriesPropertiesFromTable: command-ref/SetTimeSeriesPropertiesFromTable/SetTimeSeriesPropertiesFromTable.md
  - SetToMax: command-ref/SetToMax/SetToMax.md
  - SetToMin: command-ref/SetToMin/SetToMin.md
  - SetWarningLevel: command-ref/SetWarningLevel/SetWarningLevel.md
  - SetWorkingDir: command-ref/SetWorkingDir/SetWorkingDir.md
  - ShiftTimeByInterval: command-ref/ShiftTimeByInterval/ShiftTimeByInterval.md
  - SortTable: command-ref/SortTable/SortTable.md
  - SortTimeSeries: command-ref/SortTimeSeries/SortTimeSeries.md
  - SplitTableColumn: command-ref/SplitTableColumn/SplitTableColumn.md
  - SplitTableRow: command-ref/SplitTableRow/SplitTableRow.md
  - StartLog: command-ref/StartLog/StartLog.md
  - StartRegressionTestResultsReport: command-ref/StartRegressionTestResultsReport/StartRegressionTestResultsReport.md
  - Subtract: command-ref/Subtract/Subtract.md
  - TableMath: command-ref/TableMath/TableMath.md
  - TableTimeSeriesMath: command-ref/TableTimeSeriesMath/TableTimeSeriesMath.md
  - TableToTimeSeries: command-ref/TableToTimeSeries/TableToTimeSeries.md
  - TimeSeriesToTable: command-ref/TimeSeriesToTable/TimeSeriesToTable.md
  - UnknownCommand: command-ref/UnknownCommand/UnknownCommand.md
  - UnzipFile: command-ref/UnzipFile/UnzipFile.md
  - Wait: command-ref/Wait/Wait.md
  - WebGet: command-ref/WebGet/WebGet.md
  - WeightTraces: command-ref/WeightTraces/WeightTraces.md
  - WriteCheckFile: command-ref/WriteCheckFile/WriteCheckFile.md
  - WriteCommandSummaryToFile: command-ref/WriteCommandSummaryToFile/WriteCommandSummaryToFile.md
  - WriteDateValue: command-ref/WriteDateValue/WriteDateValue.md
  - WriteDelimitedFile: command-ref/WriteDelimitedFile/WriteDelimitedFile.md
  - WritePropertiesToFile: command-ref/WritePropertiesToFile/WritePropertiesToFile.md
  - WriteTableToDataStore: command-ref/WriteTableToDataStore/WriteTableToDataStore.md
  - WriteTableToDelimitedFile: command-ref/WriteTableToDelimitedFile/WriteTableToDelimitedFile.md
  - WriteTableToExcel: command-ref/WriteTableToExcel/WriteTableToExcel.md
  - WriteTableToHTML: command-ref/WriteTableToHTML/WriteTableToHTML.md
  - WriteTimeSeriesPropertiesToFile: command-ref/WriteTimeSeriesPropertiesToFile/WriteTimeSeriesPropertiesToFile.md
  - WriteTimeSeriesToDataStore: command-ref/WriteTimeSeriesToDataStore/WriteTimeSeriesToDataStore.md
  - WriteTimeSeriesToDataStream: command-ref/WriteTimeSeriesToDataStream/WriteTimeSeriesToDataStream.md
- Reference - Datastores:
  - Overview: datastore-ref/overview.md
  - Colorado HydroBase: datastore-ref/CO-HydroBase/CO-HydroBase.md
  - DateValue: datastore-ref/DateValue/DateValue.md
  - Generic Database: datastore-ref/GenericDatabase/GenericDatabase.md
  - StateMod Model: datastore-ref/StateMod/StateMod.md
- 'Appendix - Install TSTool': appendix/install.md
- 'Appendix - TSView Time Series Viewing Tools': appendix/tsview.md
- 'Appendix - GeoView Mapping Tools': appendix/geoview.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
# Don't enable the repo URL because irritating edit icons are shown when editing really isn't allowed
#repo_url:  https://github.com/OpenWaterFoundation/cdss-app-tstool-doc-user
site_description:  CDSS Learn TSTool
site_author:  OpenCDSS
site_favicon:  'images/opencdss-favicon.ico'
copyright:  Copyright State of Colorado
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
markdown_extensions:
  - footnotes
